//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detailorder
    {
        public int Detailid { get; set; }
        public int OrderID { get; set; }
        public int MenuID { get; set; }
        public int Qty { get; set; }
        public int Price { get; set; }
        public string Status { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Headorder Headorder { get; set; }
    }
}
